spring.application.name=emna-crud
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.url=jdbc:mysql://localhost:3306/emna_crud
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update

## cors
app.cors.enable=true
app.cors.origins=http://localhost:4200,http://localhost:3000